/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package efficax;

import java.awt.Font;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Moises
 */
public class menuOptions1 extends javax.swing.JFrame {

    /**
     * Creates new form menuOptions1
     */
    public menuOptions1() {
        initComponents();
        SetImage1();
        this.setLocationRelativeTo(null);
        setHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtArea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCursos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        myButton2 = new efficax.MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable1 = new javax.swing.JTable();
        myButton3 = new efficax.MyButton();
        myButton4 = new efficax.MyButton();
        backButton1 = new efficax.MyButton();
        myButton6 = new efficax.MyButton();
        txtHoras = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelImage1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Minimizar tiempo de estudio");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(216, 248, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });
        jPanel1.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Área de estudio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 130, 30));

        txtCursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Cantidad mínima de cursos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 220, 30));

        myButton2.setBackground(new java.awt.Color(255, 255, 102));
        myButton2.setText("Agregar");
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton2.setRadius(35);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 190, 40));

        dataTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Área de estudio", "Cantidad mínima de cursos", "Tiempo total de horas a dedicar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(dataTable1);
        if (dataTable1.getColumnModel().getColumnCount() > 0) {
            dataTable1.getColumnModel().getColumn(0).setPreferredWidth(185);
            dataTable1.getColumnModel().getColumn(1).setPreferredWidth(160);
            dataTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 640, 150));

        myButton3.setBackground(new java.awt.Color(120, 253, 218));
        myButton3.setText("Borrar datos");
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        myButton3.setRadius(35);
        jPanel1.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 190, 40));

        myButton4.setBackground(new java.awt.Color(154, 246, 73));
        myButton4.setForeground(new java.awt.Color(51, 51, 51));
        myButton4.setText("Calcular");
        myButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        myButton4.setRadius(35);
        jPanel1.add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 160, 50));

        backButton1.setBackground(new java.awt.Color(102, 0, 102));
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setText("Regresar");
        backButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        backButton1.setRadius(35);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 50));

        myButton6.setBackground(new java.awt.Color(252, 218, 81));
        myButton6.setText("Borrar fila seleccionada");
        myButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        myButton6.setRadius(35);
        jPanel1.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 190, 40));

        txtHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoras.setToolTipText("");
        jPanel1.add(txtHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 210, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INGRESO DE DATOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("a dedicar en el semestre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Tiempo total de horas ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        MainWindow principal = new MainWindow();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        //Agregando datos a la tabla y validando campos
        String area      = this.txtArea.getText();
        String cantidad  = this.txtCursos.getText();
        String horas     = this.txtHoras.getText();
        
        //Validar campos llenos
        try {
            if(area.equals("") || cantidad.equals("") || horas.equals("")){
            JOptionPane.showMessageDialog(
                    this, "Debe llenar todos los campos");
            }
            else
                //Validar que cantidad y horas sean de tipo int y mayores a 0
                if(search_digit(cantidad)==false){
                    JOptionPane.showMessageDialog(
                            this, "La cantidad debe ser un número");
                }else if(Double.parseDouble(cantidad)<=0){
                    JOptionPane.showMessageDialog(
                            this, "La cantidad debe ser positiva");
                }

                else
                    if(search_digit(horas)==false){
                        JOptionPane.showMessageDialog(
                            this, "El tiempo debe ser un número");
                    }else if(Double.parseDouble(horas)<=0){
                        JOptionPane.showMessageDialog(
                            this, "Las horas deben ser positivas");
                    }

                    else{
                        System.out.println("Todo bien");
                    }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                            this, "Los datos ingresados no son válidos");
        }
    }//GEN-LAST:event_myButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuOptions1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuOptions1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuOptions1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuOptions1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuOptions1().setVisible(true);
            }
        });
    }
    
    private void setHeader(){
        JTableHeader th;
        th = this.dataTable1.getTableHeader();
        Font fuente = new Font("Verdana", Font.BOLD,12);
        th.setFont(fuente);
    }
    
    private void SetImage1(){
        ImageIcon image = new ImageIcon(
                            getClass().getResource("/images/imageR1.png"));
        Icon icon = new ImageIcon(
                        image.getImage().getScaledInstance(
                                this.labelImage1.getWidth(), 
                                this.labelImage1.getHeight(), 
                                Image.SCALE_DEFAULT));
        this.labelImage1.setIcon(icon);
        this.repaint();
    }
    
    private boolean search_digit(String s){
  
        // Function to check if is digit
        // is found or not
        for (int i = 0; i < s.length(); i++) {
            if (Character.isDigit(
                    s.charAt(i))
                == true) {
                // return position of digit
                return true;
            }
        }
        // return 0 if digit not present
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private efficax.MyButton backButton1;
    private javax.swing.JTable dataTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImage1;
    private efficax.MyButton myButton2;
    private efficax.MyButton myButton3;
    private efficax.MyButton myButton4;
    private efficax.MyButton myButton6;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCursos;
    private javax.swing.JTextField txtHoras;
    // End of variables declaration//GEN-END:variables
}
